version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=development
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=bot_management
      - REDIS_HOST=redis
      - JWT_SECRET=dev-secret-key-change-in-production
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    networks:
      - bot-management-network

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: bot_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bot-management-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - bot-management-network

volumes:
  postgres_data:
  redis_data:

networks:
  bot-management-network:
    driver: bridge